### ISSUE TITLE
Checklist of which Librosa functions are in Pliers

### ISSUE THREAD

**Issue by koudyk** [tyarkoni/pliers#354]
# Checklist of which Librosa functions are in Pliers

How to understand this checklist:
- I **bolded** functions that aren't in Pliers and might be useful.
- I put as star \* beside functions that aren't in Pliers and I'm not sure whether they'd be useful because I don't understand what they do.
- I made some notes in *italics*.
- For the most part, I'm thinking about what could be useful in Neuroscout. E.g., I left out functions that change the audio (pitch shifting, time warping)

[Link to the Librosa docs](https://librosa.github.io/librosa/)

### SPECTRAL
- [x] chroma\_stft
- [x] chroma\_cqt
- [x] chroma\_cens
- [x] melspectrogram
- [x] mfcc
- [x] rms
- [x] spectral\_centroid
- [x] spectral\_bandwidth
- [x] spectral\_contrast
- [x] spectral\_flatness
- [x] spectral\_rolloff
- [x] poly\_features
- [x] tonnetz
- [x] zero\_crossing\_rate

### AUDITORY
- [x] tempogram

### FEATURE MANIPULATION
*(These functions might be useful in the transformations tab in Neuroscout)*
- [ ] **delta**
- [ ] **stack\_memory**

## ONSET DETECTION
- [x] onset\_detect
- [ ] onset\_backtrack
- [ ] **onset\_strength** *(This function would be useful if you want a single vector of onset strength rather than a vector for each frequency band, which is what the next function gives you. In Neuroscout, for example, I think that users likely wouldn't need onset strengths for every frequency band.)*
- [x] onset\_strength\_multi

## BEAT AND TEMPO
- [x] beat\_track
- [x] tempo

## SPECTROGRAM DECOMPOSITION
- [ ] decompose
- [ ] **hpss** *(This function is called by the harmonic-percussive source separation functions below, but returns time-frequency representations of the harmonic and percussive sources, not time-series. I can't see it being useful for Neuroscout, but it might be useful for other applications)*
- [ ] nn\_filter

### HARMONIC-PERCUSSIVE SOURCE SEPARATION
- [ ] hpss *(Redundant with the combination of the next two functions.)*
- [x] harmonic
- [x] percussive

### RECURRENCE AND SELF-SIMILARITY
*(Might be useful in Neuroscout for investigating something like the neural correlates of echoic or short-term memory)*
- [ ] **recurrence\_matrix**
- [ ] **recurrence\_to\_lag**
- [ ] lag\_to\_recurrence
- [ ] timelag\_filter

### TEMPORAL CLUSTERING
(*Might be useful in Neuroscout for comparing the temporal structure of stimuli and brain responses*)
- [x] **agglomerative**
- [x] **subsegment**

### VITERBI DECODING
- [ ] viterbi \*
- [ ] viterbi\_discriminative \*
- [ ] viterbi\_binary \*

### TRANSITION MATRICES
- [ ] transitions\_uniform \*
- [ ] transitions\_loop \*
- [ ] transitions\_cycle \*
- [ ] transitions\_local \*

**Comment by adelavega** [comment]
Amazing! Thank you so much. This is a very helpful roadmap :)

**Comment by PeerHerholz** [comment]
Thx @koudyk, this is amazing. If you would be up, we could start working on this together, otherwise, I'd start to do it this week. Anyhow, we should track which functions we added here. @adelavega: how should we organize PRs, one big one with functions or smaller ones based on e.g., the feature type?

**Comment by PeerHerholz** [comment]
@koudyk and I had a brief meeting and decided to open a branch to implement the missing librosa functions. Once we have something, we'll check how to organize the PRs.

**Comment by tyarkoni** [comment]
That sound awesome, thanks! Re: PR, one big one would probably be easier from a reviewing standpoint, but if you find multiple smaller ones more efficient, that's also totally fine.

**Comment by adelavega** [comment]
@rbroc this is a listing of Librosa features in pliers, take a look!

**Comment by PeerHerholz** [comment]
JFYI: @koudyk and I are still working on implementing the missing features. Should have them ready soon!

**Comment by adelavega** [comment]
hey @PeerHerholz did you ever get a chance to work on this? If not no worries just wondering

**Comment by PeerHerholz** [comment]
Yeah, I did start working on same features in my fork, but only finished some...

**Comment by adelavega** [comment]
ah okay just wondering. i was just perusing older issues.

if you have anything that partially covers some of this that is done and you'd like to submit go for it though.
